name: Generate Daily Newsletter

on:
  schedule:
    # Run at 7:00 AM Pacific Time (14:00 UTC in winter, 15:00 UTC in summer)
    - cron: '0 15 * * *'  # 7 AM PST (adjust for your timezone)
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode (uses cached data if available)'
        required: false
        default: 'false'

permissions:
  contents: write  # Required to push to GitHub Pages repository
  pages: write
  id-token: write

jobs:
  generate-newsletter:
    runs-on: ubuntu-latest
    timeout-minutes: 25  # GitHub Actions free tier has 30min limit
    
    steps:
      # Checkout the newsletter agent code
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      # Install dependencies
      - name: Install Dependencies
        run: npm ci
      
      # Build the TypeScript project
      - name: Build Project
        run: npm run build
      
      # Create cache directory
      - name: Setup Cache Directory
        run: mkdir -p tmp/cache
      
      # Generate the newsletter
      - name: Generate Newsletter
        env:
          # AI Provider Configuration (defaults to free tier)
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER || 'free' }}
          MONTHLY_BUDGET_LIMIT: ${{ secrets.MONTHLY_BUDGET_LIMIT || '0.00' }}
          
          # AI Provider API Keys (only required for your chosen tier)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          
          # Core Infrastructure
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ secrets.GITHUB_PAGES_REPO || github.repository }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_BRANCH: main
          
          # Optional External APIs
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          
          # Newsletter Configuration
          NEWSLETTER_TIME: "07:00"
          TIMEZONE: "America/Los_Angeles"
          MAX_ARTICLES: 15
          
          # Cloud Configuration
          CACHE_DIR: "./tmp/cache"
          LOG_LEVEL: "info"
          DEBUG_MODE: false
          
          # Private URL Authentication
          FEEDBACK_SECRET: ${{ secrets.FEEDBACK_SECRET }}
          
          # Email Notification (for later implementation)
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          
          # Test mode flag
          TEST_MODE: ${{ github.event.inputs.test_mode || 'false' }}
          
        run: node dist/index.js
      
      # Upload logs as artifacts for debugging
      - name: Upload Logs
        if: always()  # Upload logs even if previous step failed
        uses: actions/upload-artifact@v4
        with:
          name: newsletter-logs-${{ github.run_number }}
          path: |
            logs/*.log
            tmp/cache/*.json
          retention-days: 7
      
      # Send success notification (optional)
      - name: Notify Success
        if: success()
        run: |
          echo "✅ Newsletter generated successfully at $(date)"
          echo "🔗 Check your GitHub Pages site for the latest newsletter"
      
      # Send failure notification (optional)
      - name: Notify Failure
        if: failure()
        run: |
          echo "❌ Newsletter generation failed at $(date)"
          echo "📋 Check the logs artifact for debugging information"